export const link = "https://solipresse.herokuapp.com/api";

export const linkSocket = "https://solipresse.herokuapp.com";

//Alert 

export const SET_ALERT = "SET_ALERT";
export const  REMOVE_ALERT = " REMOVE_ALERT";

// Auth

// Sign In

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

//Sign Up

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

//Complete Registration

export const COMPLETE_REGISTRATION_REQUEST = "COMPLETE_REGISTRATION_REQUEST";
export const COMPLETE_REGISTRATION_SUCCESS = "COMPLETE_REGISTRATION_SUCCESS";
export const COMPLETE_REGISTRATION_FAIL = "COMPLETE_REGISTRATION_FAIL";

// Get user details

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

//Post

export const NEW_ARTICLE_REQUEST = "NEW_ARTICLE_REQUEST";
export const NEW_ARTICLE_SUCCESS = "NEW_ARTICLE_SUCCESS";
export const NEW_ARTICLE_FAIL = "NEW_ARTICLE_FAIL";

export const GET_ARTICLE_REQUEST = "GET_ARTICLE_REQUEST";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_FAIL = "GET_ARTICLE_FAIL";

export const EDIT_ARTICLE_REQUEST = "EDIT_ARTICLE_REQUEST";
export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS";
export const EDIT_ARTICLE_FAIL = "EDIT_ARTICLE_FAIL";

export const UPDATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAIL = "UPDATE_ARTICLE_FAIL";

export const REMOVED_ARTICLE_REQUEST = "REMOVED_ARTICLE_REQUEST";
export const REMOVED_ARTICLE_SUCCESS = "REMOVED_ARTICLE_SUCCESS";
export const REMOVED_ARTICLE_FAIL = "REMOVED_ARTICLE_FAIL";

export const ALL_ARTICLE_REQUEST = "ALL_ARTICLE_REQUEST";
export const ALL_ARTICLE_SUCCESS = "ALL_ARTICLE_SUCCESS";
export const ALL_ARTICLE_FAIL = "ALL_ARTICLE_FAIL";

export const DRAFTS_ARTICLE_REQUEST = "DRAFTS_ARTICLE_REQUEST";
export const DRAFTS_ARTICLE_SUCCESS = "DRAFTS_ARTICLE_SUCCESS";
export const DRAFTS_ARTICLE_FAIL = "DRAFTS_ARTICLE_FAIL";

export const CATEGORY_ARTICLE_REQUEST = "CATEGORY_ARTICLE_REQUEST";
export const CATEGORY_ARTICLE_SUCCESS = "CATEGORY_ARTICLE_SUCCESS";
export const CATEGORY_ARTICLE_FAIL = "CATEGORY_ARTICLE_FAIL";

export const AUTHOR_ARTICLE_REQUEST = "AUTHOR_ARTICLE_REQUEST";
export const AUTHOR_ARTICLE_SUCCESS = "AUTHOR_ARTICLE_SUCCESS";
export const AUTHOR_ARTICLE_FAIL = "AUTHOR_ARTICLE_FAIL";


//Comment 

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const ADD_REPLY_COMMENT_REQUEST = "ADD_REPLY_COMMENT_REQUEST";
export const ADD_REPLY_COMMENT_SUCCESS = "ADD_REPLY_COMMENT_SUCCESS";
export const ADD_REPLY_COMMENT_FAIL = "ADD_REPLY_COMMENT_FAIL";

export const FETCH_COMMENT_REQUEST = "FETCH_COMMENT_REQUEST";
export const FETCH_COMMENT_SUCCESS = "FETCH_COMMENT_SUCCESS";
export const FETCH_COMMENT_FAIL = "FETCH_COMMENT_FAIL";

export const LIKE_REQUEST = "LIKE_REQUEST";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAIL = "LIKE_FAIL";

export const UNLIKE_REQUEST = "UNLIKE_REQUEST";
export const UNLIKE_SUCCESS = "UNLIKE_SUCCESS";
export const UNLIKE_FAIL = "UNLIKE_FAIL";

export const ISLIKE_REQUEST = "ISLIKE_REQUEST";
export const ISLIKE_SUCCESS = "ISLIKE_SUCCESS";
export const ISLIKE_FAIL = "ISLIKE_FAIL";

//User

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const DETAILS_USER_REQUEST = "DETAILS_USER_REQUEST";
export const DETAILS_USER_SUCCESS = "DETAILS_USER_SUCCESS";
export const DETAILS_USER_FAIL = "DETAILS_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const APPROVED_USER_REQUEST = "APPROVED_USER_REQUEST";
export const APPROVED_USER_SUCCESS = "APPROVED_USER_SUCCESS";
export const APPROVED_USER_FAIL = "APPROVED_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";